name: Linter

on: push

jobs:
  lint:
    name: lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
<<<<<<< HEAD
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
=======
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>>>>>>> fdc1a947121d0ab3fd69afaa0b4e60cf587c18da
